### ISSUE TITLE
Cannot install v4r via apt-get

### ISSUE THREAD

**Issue by danielzuegner** [squirrel-project/squirrel_perception#142] opened 2017-04-07 10:07 UTC
I've followed the instructions of how to install the new v4r binary:

`roscd squirrel_perception`
and then
`./setup.bash`

But `sudo apt-get update` now gives the following error:
`Failed to fetch http://153.97.4.193/building/ubuntu/dists/xenial/InRelease  Could not connect to 153.97.4.193:80 (153.97.4.193), connection timed out`

Also, pinging this address fails. Consequently, 
`sudo apt-get install v4r` yields 

`E: Unable to locate package v4r`

I've compiled the latest v4r release from source. In `catkin_make`, this leads to errors that `v4r/segmentation/dominant_plane_segmenter.h`cannot be found.

Compiling v4r from the current Git sources lead to errors in `catkin_make`: `'DominantPlaneSegmenterParameter' is not a member of 'v4r'`

Do you have any suggestion of how to solve this?

Thanks!

Daniel

**Comment by bajo** [comment] 2017-04-07 11:27
It seems that our repo server is offline right now. 
@ipa-nhg Can you please check why it is offline? 

@danielzuegner Unfortunately there are different versions of v4r available right now. We are in the process of getting solving this issue in the near future. Therefore I have to ask you from which git repo you pulled the v4r source?
Thanks.

**Comment by danielzuegner** [comment] 2017-04-07 11:34
@bajo Thank you for the quick response. 

I pulled the v4r sources from [this page](https://github.com/strands-project/v4r). First I tried release 1.4.3, and then I did a plain 'git clone' of the repo.

**Comment by tpatten** [comment] 2017-04-07 11:42
@danielzuegner If the IPA server does not come online soon we can send you the debian package by email.

**Comment by danielzuegner** [comment] 2017-04-07 11:46
@tpatten that would be great. I'll send you an email so that you have my address.

**Comment by bajo** [comment] 2017-04-07 11:48
@danielzuegner That is the version we use within the STRANDS project and has not been updated because we did not want to risk any regressions during the final project phase.
You can use [V4R](https://rgit.acin.tuwien.ac.at/root/v4r) for the source or download the package from our buildserver [https://rgit.acin.tuwien.ac.at/root/v4r/pipelines/475/builds](https://rgit.acin.tuwien.ac.at/root/v4r/pipelines/475/builds) Just click on the download artifacts button.

**Comment by ipa-nhg** [comment] 2017-04-12 11:03
Sorry I didn't see this before. 
The IPA server is again available we had some network problems, sorry... but @danielzuegner are you using Ubuntu 16.04 (your sudo apt-get update said that you are looking for the Xenial distro) ? This may not work, we still didn't migrate the packages to kinetic

**Comment by danielzuegner** [comment] 2017-04-13 08:43
Thank you all for your help. I was able to get v4r and squirrel_perception compiled on an Ubuntu 14.04 machine. However, the v4r classification as described in [here](https://rgit.acin.tuwien.ac.at/root/v4r/blob/master/docs/ObjectClassification.md) seems to require a graphics card, which this machine doesn't have. My Ubuntu 16.04 computer does have a GPU, but I guess I'm out of luck there.

**Comment by tpatten** [comment] 2017-04-13 09:10
Yes it is true. A graphics card is required in order to render the views of the CAD models. I am uploading a small set of models to my dropbox and will shortly send you a link so you can download.

**Comment by bajo** [comment] 2017-04-19 08:25
Installation works now. Closing the issue.

**Closed as completed by bajo** 2017-04-19 08:25 UTC
